name: health report

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '10 0 * * *'
  workflow_dispatch:

jobs:
  report:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Health Report
      run: |
        pip install -r ./requirements.txt
        Set-TimeZone -Name "China Standard Time"
        python ./jksb_sysu.py
      env:
        netid: ${{secrets.NETID}}
        password: ${{secrets.PASSWORD}}
        ocr_token: ${{secrets.OCR_TOKEN}}
        tg_bot_token: ${{secrets.TG_BOT_TOKEN}}
        tg_chatid: ${{secrets.TG_CHATID}}
